### ISSUE TITLE
problem di Nginx

### ISSUE THREAD

**Issue by fariztha** [bisanedev/framework#2]
Server nginx1.18, windows 10 64x, environment sdh di test semua, worked
tetapi ketika mengakses localhost: file public gk bisa diakses 403
belum ketemu solusinya ini... kyknya ada sesuatu di path atau relative directory nya
tapi coba pakai info.php bisa, akses index.php gk bisa

[access.log](https://github.com/bisanedev/framework/files/5898863/access.log)
[error.log](https://github.com/bisanedev/framework/files/5898864/error.log)

**Comment by fariztha** [comment]
![image](https://user-images.githubusercontent.com/5076562/106369815-1476d900-6387-11eb-9d2a-2a8d0eaa0751.png)

**Comment by bisanedev** [comment]
Coba ini dulu @fariztha , pakai converter di internet , disini aku gak pakai nginx
`location / {
  if (!-e $request_filename){
    rewrite ^(.*)$ /index.php break;
  }
}`

**Comment by fariztha** [comment]
ah mod rewrite nya harus versi nginx jg ya, sudah sementara di skip saja yang ini
